# Generated by Django 4.1.2 on 2022-10-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicle_Number', models.IntegerField()),
                ('Vehicle_Type', models.CharField(max_length=255)),
                ('Vehicle_Model', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
