# Generated by Django 4.1.2 on 2022-10-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vechicleapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledata',
            name='Vehicle_Number',
            field=models.CharField(max_length=25),
        ),
    ]
