# Generated by Django 4.1.2 on 2022-10-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vechicleapp', '0003_alter_vehicledata_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledata',
            name='Vehicle_Type',
            field=models.CharField(choices=[('Two wheeler', 'Two wheeler'), ('Three wheeler', 'Three wheeler'), ('Four wheeler', 'Four wheeler')], max_length=255, null=True),
        ),
    ]
